"""create incident history table

Revision ID: 0a2472011d12
Revises: 3fc80053f985
Create Date: 2026-09-15 01:54:54.889277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2472011d12'
down_revision: Union[str, Sequence[str], None] = '3fc80053f985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_history_actor_id'), 'incident_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_incident_history_id'), 'incident_history', ['id'], unique=False)
    op.create_index(op.f('ix_incident_history_incident_id'), 'incident_history', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_history_organization_id'), 'incident_history', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_history_organization_id'), table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_incident_id'), table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_id'), table_name='incident_history')
    op.drop_index(op.f('ix_incident_history_actor_id'), table_name='incident_history')
    op.drop_table('incident_history')
    # ### end Alembic commands ###
