"""create sla escalations table

Revision ID: 3267dfe6c450
Revises: 330932c0aa5e
Create Date: 2026-09-16 01:36:37.550635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3267dfe6c450'
down_revision: Union[str, Sequence[str], None] = '330932c0aa5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('breach_type', sa.String(length=30), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'breach_type', 'escalation_level', name='uq_incident_breach_escalation_level')
    )
    op.create_index(op.f('ix_sla_escalations_id'), 'sla_escalations', ['id'], unique=False)
    op.create_index(op.f('ix_sla_escalations_incident_id'), 'sla_escalations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_sla_escalations_organization_id'), 'sla_escalations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_escalations_organization_id'), table_name='sla_escalations')
    op.drop_index(op.f('ix_sla_escalations_incident_id'), table_name='sla_escalations')
    op.drop_index(op.f('ix_sla_escalations_id'), table_name='sla_escalations')
    op.drop_table('sla_escalations')
    # ### end Alembic commands ###
