"""add sla fields to incidents

Revision ID: 330932c0aa5e
Revises: a9c190f39f6f
Create Date: 2026-09-15 19:39:33.011178

""" 
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330932c0aa5e'
down_revision: Union[str, Sequence[str], None] = 'a9c190f39f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('sla_policy_id', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_incidents_sla_policy_id'), 'incidents', ['sla_policy_id'], unique=False)
    op.create_foreign_key(
    'fk_incidents_sla_policy_id',
    'incidents',
    'sla_policies',
    ['sla_policy_id'],
    ['id']
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        'fk_incidents_sla_policy_id',
        'incidents',
         type_='foreignkey'
    )
    op.drop_index(op.f('ix_incidents_sla_policy_id'), table_name='incidents')
    op.drop_column('incidents', 'first_response_at')
    op.drop_column('incidents', 'resolution_due_at')
    op.drop_column('incidents', 'response_due_at')
    op.drop_column('incidents', 'sla_policy_id')
    # ### end Alembic commands ###
