"""create incident comments table

Revision ID: 3fc80053f985
Revises: 4eb288e83baa
Create Date: 2026-09-15 01:00:29.108516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc80053f985'
down_revision: Union[str, Sequence[str], None] = '4eb288e83baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_comments_author_id'), 'incident_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_incident_comments_id'), 'incident_comments', ['id'], unique=False)
    op.create_index(op.f('ix_incident_comments_incident_id'), 'incident_comments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_comments_organization_id'), 'incident_comments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_comments_organization_id'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_incident_id'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_id'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_author_id'), table_name='incident_comments')
    op.drop_table('incident_comments')
    # ### end Alembic commands ###
