"""create automation rules table

Revision ID: 41f3215dadde
Revises: fabe2e33e36f
Create Date: 2026-09-23 23:58:14.087554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f3215dadde'
down_revision: Union[str, Sequence[str], None] = 'fabe2e33e36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('assign_to_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assign_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_assign_to_user_id'), 'automation_rules', ['assign_to_user_id'], unique=False)
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_automation_rules_organization_id'), 'automation_rules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_rules_organization_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_assign_to_user_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
